apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
---
apiVersion: v1
kind: Namespace
metadata:
  name: crontab-plugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crontab-plugin
  namespace: crontab-plugin
  labels:
    app: crontab-plugin
    app.kubernetes.io/component: crontab-plugin
    app.kubernetes.io/instance: crontab-plugin
    app.kubernetes.io/part-of: crontab-plugin
    app.openshift.io/runtime-namespace: crontab-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crontab-plugin
  template:
    metadata:
      labels:
        app: crontab-plugin
    spec:
      containers:
        - name: crontab-plugin
          image: quay.io/jcaianirh/crontab-plugin
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          args:
            - '--ssl'
            - '--cert=/var/serving-cert/tls.crt'
            - '--key=/var/serving-cert/tls.key'
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: crontab-plugin
  namespace: crontab-plugin
  labels:
    app: crontab-plugin
    app.kubernetes.io/component: crontab-plugin
    app.kubernetes.io/instance: crontab-plugin
    app.kubernetes.io/part-of: crontab-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: crontab-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: crontab-plugin
spec:
  backend:
    service:
      basePath: /
      name: crontab-plugin
      namespace: crontab-plugin
      port: 9001
    type: Service
  displayName: CronTab Plugin
  i18n:
    loadType: Preload
