apiVersion: v1
kind: Namespace
metadata:
  name: crontab-plugin
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crontab-plugin
  namespace: crontab-plugin
  labels:
    app: crontab-plugin
    app.kubernetes.io/component: crontab-plugin
    app.kubernetes.io/instance: crontab-plugin
    app.kubernetes.io/part-of: crontab-plugin
    app.openshift.io/runtime-namespace: ccrontab-plugin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crontab-plugin
  template:
    metadata:
      labels:
        app: crontab-plugin
    spec:
      containers:
        - name: crontab-plugin
          image: docker.io/raspbeep/crontab-plugin:latest
          ports:
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: plugin-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
            - name: nginx-conf
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
            defaultMode: 420
        - name: nginx-conf
          configMap:
            name: nginx-conf
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: crontab-plugin
  labels:
    app: crontab-plugin
    app.kubernetes.io/part-of: crontab-plugin
data:
  nginx.conf: |
    error_log /dev/stdout info;
    events {}
    http {
      access_log         /dev/stdout;
      include            /etc/nginx/mime.types;
      default_type       application/octet-stream;
      keepalive_timeout  65;
      server {
        listen              9443 ssl;
        ssl_certificate     /var/serving-cert/tls.crt;
        ssl_certificate_key /var/serving-cert/tls.key;
        root                /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
  name: crontab-plugin
  namespace: crontab-plugin
  labels:
    app: crontab-plugin
    app.kubernetes.io/component: crontab-plugin
    app.kubernetes.io/instance: crontab-plugin
    app.kubernetes.io/part-of: crontab-plugin
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: crontab-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: crontab-plugin
spec:
  displayName: 'OpenShift CronTab Plugin'
  backend:
    type: Service
    service:
      name: crontab-plugin
      namespace: crontab-plugin
      port: 9443
      basePath: '/'
